services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_bim_iot
    ports:
      - "8086:8086"
    volumes:
      - bim-iot_influxdb_data:/var/lib/influxdb2
      - bim-iot_influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
    networks:
      - bim-iot_network

  graphdb:
    image: ontotext/graphdb:10.7.0
    container_name: graphdb_bim_iot
    ports:
      - "7200:7200"
    volumes:
      - bim-iot_graphdb_data:/opt/graphdb/home
    networks:
      - bim-iot_network
  neo4j:
    image: neo4j:5.12.0
    container_name: neo4j_bim_iot
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - bim-iot_neo4j_data:/data
      - bim-iot_neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc", "n10s"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,n10s.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,n10s.*
    networks:
      - bim-iot_network

#  streamlit:
#    build: .
#    container_name: streamlit_bim_iot
#    ports:
#      - "8501:8501"
#    volumes:
#      - .:/app
#      - ./.streamlit:/app/.streamlit
#    depends_on:
#      - influxdb
#      - graphdb
#      - neo4j
#    networks:
#      - bim-iot_network

networks:
  bim-iot_network:
    driver: bridge

volumes:
  bim-iot_influxdb_data:
  bim-iot_influxdb_config:
  bim-iot_graphdb_data:
  bim-iot_neo4j_data:
  bim-iot_neo4j_logs: